import Foundation

// MARK: - In-app localization (runtime language switch)
func L(_ key: String) -> String {
    let lang = SettingsManager.shared.appLanguage
    if lang == "English" { return key }
    return translations[lang]?[key] ?? key
}

private let translations: [String: [String: String]] = [
    "中文": [
        // Tabs
        "My Holdings": "我的持仓",
        "News": "新闻",
        "More": "更多",
        "Gurus": "大佬持仓",
        // Market status
        "Open": "开盘中",
        "Pre-Market": "盘前交易",
        "After-Hours": "盘后交易",
        "Closed": "已收盘",
        // Investor view
        "Guru Portfolios": "大佬持仓",
        "SEC 13F filings from top investors": "顶级投资者的 SEC 13F 持仓披露",
        "Filing Date": "申报日期",
        "Total Value": "总市值",
        "Top Holdings": "主要持仓",
        "All Holdings": "全部持仓",
        "Company": "公司",
        "Value": "市值",
        "Shares": "股数",
        "Other": "其他",
        // MyHoldingView & Add Asset
        "No stocks in watchlist": "自选列表为空",
        "Enter Stock Symbol": "输入股票代码",
        "e.g. AAPL, MSFT": "例如 AAPL, MSFT",
        "Add": "添加",
        "Cancel": "取消",
        "Add Asset": "添加资产",
        "Stocks": "股票",
        "Crypto": "加密货币",
        "Metals": "贵金属",
        "Commodity": "大宗商品",
        "Search stocks": "搜索股票",
        "Search crypto": "搜索加密货币",
        "Search forex": "搜索外汇",
        "Search metals": "搜索贵金属",
        "Search commodities": "搜索大宗商品",
        "Forex": "外汇",
        "Popular": "热门",
        // Interests
        "What interests you?": "你对什么感兴趣？",
        "My Interests": "我的兴趣",
        "Pick your favorite categories to get personalized recommendations": "选择你感兴趣的类别，获取个性化推荐",
        "Update your interests for better recommendations": "更新你的兴趣以获取更好的推荐",
        "selected": "已选",
        "Skip for now": "暂时跳过",
        "Continue": "继续",
        "Save": "保存",
        "Not set": "未设置",
        "Recommended for You": "为你推荐",
        "Based on your interests": "基于你的兴趣",
        // Today's Market
        "Today's Market": "今日行情",
        "Hot": "热门",
        "Gainers": "涨幅榜",
        "Losers": "跌幅榜",
        "My Movers": "我的涨跌",
        "No data available": "暂无数据",
        "Add more to see movers": "添加更多以查看涨跌",
        "Today": "今日",
        "Touch to explore": "触摸查看详情",
        "Watchlist": "自选列表",
        "Something went wrong": "出了点问题",
        "Try Again": "重试",
        // Interest categories
        "Technology": "科技",
        "Finance": "金融",
        "Healthcare": "医疗健康",
        "Energy": "能源",
        "Consumer": "消费",
        "Real Estate": "房地产",
        "Industrial": "工业",
        "Telecom": "通信传媒",
        "Cryptocurrency": "加密货币",
        "Precious Metals": "贵金属",
        "Commodities": "大宗商品",
        "ETFs & Index": "ETF 与指数",
        "Dividends": "高股息",
        // NewsView - date handled separately
        // ChatView
        "Orion AI": "Orion AI",
        "No conversations yet": "暂无对话记录",
        "Start a new chat": "开始新对话",
        "Temporary Chat": "临时对话",
        "Thinking...": "思考中...",
        "Ask Orion...": "问问 Orion...",
        "Photo attached": "已附加照片",
        "Empty chat": "空对话",
        "messages": "条消息",
        // StockDetailView
        "Loading...": "加载中...",
        "AI Analysis & Trading Suggestions": "AI 分析与交易建议",
        "Get AI-powered analysis and trading advice": "获取 AI 驱动的分析和交易建议",
        "AI Analysis": "AI 分析",
        "Ask about": "询问关于",
        "Conversation": "对话",
        "Conservative": "保守",
        "Moderate": "稳健",
        "Aggressive": "激进",
        "Generating...": "生成中...",
        "AI Decision Dashboard": "AI 决策看板",
        "Generating AI analysis...": "正在生成 AI 分析...",
        "Market Sentiment": "市场情绪",
        "Bullish Factors": "看涨因素",
        "Bearish Factors": "看跌因素",
        "Entry": "入场价",
        "Stop Loss": "止损价",
        "Target": "目标价",
        "Ask Orion for deeper analysis": "向 Orion 询问更深入的分析",
        "Fundamentals": "基本面",
        "EPS Growth": "EPS 增长",
        "Revenue Growth": "营收增长",
        "Div Yield": "股息率",
        "Gross Margin": "毛利率",
        "Op Margin": "营业利润率",
        "Very Bearish": "极度看跌",
        "Very Bullish": "极度看涨",
        "Watch": "观望",
        "Chart load failed": "图表加载失败",
        "Failed to load": "加载失败",
        "Key Data": "关键数据",
        "Open Price": "开盘价",
        "Previous Close": "前收盘价",
        "Day High": "最高价",
        "Day Low": "最低价",
        "Volume": "成交量",
        "Day Range": "日内区间",
        "52W Range": "52周区间",
        "Analyst Recommendations": "分析师建议",
        "Strong Buy": "强烈买入",
        "Buy": "买入",
        "Hold": "持有",
        "Sell": "卖出",
        "Strong Sell": "强烈卖出",
        "Related News": "相关新闻",
        "Options Activity": "期权活动",
        "Options data requires a premium data subscription.": "期权数据需要高级数据订阅。",
        "Calls": "看涨",
        "Puts": "看跌",
        "Similar Companies": "相似公司",
        "Comments": "评论",
        "Leave a comment...": "发表评论...",
        "No comments yet. Be the first!": "还没有评论，快来抢沙发！",
        "View more comments": "查看更多评论",
        "just now": "刚刚",
        "Company Info": "公司信息",
        "Industry": "行业",
        "Exchange": "交易所",
        "Country": "国家",
        "Employees": "员工数",
        "Market Cap": "市值",
        "IPO Date": "上市日期",
        "Website": "网站",
        "Connected": "已连接",
        "Connecting...": "连接中...",
        // MenuView
        "Settings": "设置",
        "Appearance": "外观",
        "Notifications": "通知",
        "On": "已开启",
        "Off": "已关闭",
        "Enable Notifications": "开启通知",
        "Monitor stocks in background": "在后台监控股票",
        "Market Index Alerts": "大盘预警",
        "Alert Threshold": "预警阈值",
        "Notify when any major index moves more than this percentage": "当大盘指数涨跌幅超过此百分比时通知",
        "Market Alerts": "大盘预警",
        "Watchlist Price Alerts": "自选股价格预警",
        "Alert on big moves in your watchlist": "自选股大幅波动时提醒",
        "Notify when a watchlist stock moves more than this percentage": "当自选股涨跌幅超过此百分比时通知",
        "Price Alerts": "价格预警",
        "Daily Market Summary": "每日市场总结",
        "Receive a summary after market close (4:05 PM ET)": "收盘后推送每日总结 (美东 4:05 PM)",
        "Daily Summary": "每日总结",
        "How it works": "工作原理",
        "Orion monitors stock prices in the background using iOS Background App Refresh. Checks happen approximately every 15-30 minutes when the market is open. For real-time alerts, keep the app open.": "Orion 使用 iOS 后台应用刷新功能在后台监控股价。开市时大约每 15-30 分钟检查一次。如需实时提醒，请保持 App 在前台运行。",
        "About": "关于",
        "Big Move": "大幅波动",
        "is up": "上涨",
        "is down": "下跌",
        "surging": "大涨",
        "dropping": "大跌",
        "Market Closed": "收盘了",
        "Tap to see today's market summary and your portfolio performance.": "点击查看今日市场总结和你的持仓表现。",
        "Language": "语言",
        "Share": "分享",
        "Support": "帮助",
        "Contact": "联系我们",
        "Copyright Info": "版权信息",
        "Log Out": "退出登录",
        "Light": "浅色",
        "Dark": "深色",
        "System": "跟随系统",
        "Done": "完成",
        // LoginView
        "Email": "邮箱",
        "Password": "密码",
        "Log In": "登录",
        "Forgot Password?": "忘记密码？",
        "Forgot Password": "忘记密码",
        "or": "或",
        "Continue with Google": "使用 Google 登录",
        "Don't have an account?": "没有账号？",
        "Sign Up": "注册",
        "Skip Login (Beta)": "跳过登录 (Beta)",
        "Email and password are required": "请输入邮箱和密码",
        "Authentication failed.": "登录失败",
        "Send Reset Link": "发送重置链接",
        "Reset link sent!": "重置链接已发送！",
        "Please enter your email": "请输入邮箱",
        // Greetings
        "Good morning": "早上好",
        "Good afternoon": "下午好",
        "Good evening": "晚上好",
        "Let's see how the market opens today": "来看看今天的市场吧",
        "A fresh start for your portfolio": "新的一天，新的机会",
        "Ready for a new trading day?": "准备好迎接新的交易日了吗？",
        "Markets are moving — stay informed": "市场正在变化 — 保持关注",
        "Here's what's happening today": "看看今天发生了什么",
        "Keep an eye on your investments": "关注你的投资动态",
        "How did your portfolio do today?": "今天你的投资组合表现如何？",
        "Time to review today's moves": "回顾一下今天的行情",
        "Markets are winding down": "市场即将收盘",
        "Rest well, markets will be here tomorrow": "好好休息，明天市场依旧在",
        "Planning ahead for tomorrow?": "为明天做好计划了吗？",
        "Take it easy tonight": "今晚放松一下",
        // Empty states
        "Your watchlist is empty": "你的自选列表是空的",
        "Start building your constellation of investments": "开始构建你的投资星座",
        "Add your first stock to start tracking": "添加第一只股票开始追踪",
        "Add Stock": "添加股票",
        "Ask Orion anything about stocks, markets, or investing": "向 Orion 提问任何关于股票、市场或投资的问题",
        "Remove from Watchlist": "从自选列表移除",
        "View Details": "查看详情",
        "Move to Top": "移到顶部",
        "Copy Info": "复制信息",
        "Copy Link": "复制链接",
        "Summarize with Orion": "用 Orion 总结",
        "Orion Summary": "Orion 总结",
        "Orion is reading the article...": "Orion 正在阅读文章...",
        "Markets are closed today — enjoy your Sunday": "今天休市 — 享受你的周日",
        "Markets are closed today — enjoy your Saturday": "今天休市 — 享受你的周六",
        "Markets are closed today for a holiday": "今天假日休市",
        "Holiday": "假日",
        "Chart Unavailable": "图表不可用",
        "Unable to Load News": "无法加载新闻",
        "Your investment companion": "你的投资伴侣",
        "Loading article...": "加载文章中...",
        "Unable to Load Article": "无法加载文章",
    ],
    "日本語": [
        "My Holdings": "保有銘柄",
        "News": "ニュース",
        "Gurus": "著名投資家",
        "Guru Portfolios": "著名投資家のポートフォリオ",
        "Filing Date": "届出日",
        "Total Value": "総額",
        "Top Holdings": "主要保有銘柄",
        "All Holdings": "全保有銘柄",
        "Company": "企業",
        "Value": "時価",
        "Shares": "株数",
        "Other": "その他",
        "Open": "取引中",
        "Pre-Market": "プレマーケット",
        "After-Hours": "アフターアワーズ",
        "Closed": "休場",
        "More": "その他",
        "No stocks in watchlist": "ウォッチリストに銘柄がありません",
        "Enter Stock Symbol": "銘柄コードを入力",
        "e.g. AAPL, MSFT": "例: AAPL, MSFT",
        "Add": "追加",
        "Cancel": "キャンセル",
        "Orion AI": "Orion AI",
        "No conversations yet": "会話履歴がありません",
        "Start a new chat": "新しいチャットを開始",
        "Temporary Chat": "一時チャット",
        "Thinking...": "考え中...",
        "Ask Orion...": "Orionに聞く...",
        "Photo attached": "写真を添付済み",
        "Empty chat": "空のチャット",
        "messages": "件のメッセージ",
        "Loading...": "読み込み中...",
        "AI Analysis & Trading Suggestions": "AI分析と取引提案",
        "Get AI-powered analysis and trading advice": "AI分析と取引アドバイスを取得",
        "AI Analysis": "AI分析",
        "Ask about": "について質問",
        "Conversation": "会話",
        "Conservative": "保守的",
        "Moderate": "中立",
        "Aggressive": "積極的",
        "Generating...": "生成中...",
        "Chart load failed": "チャートの読み込み失敗",
        "Failed to load": "読み込み失敗",
        "Settings": "設定",
        "Appearance": "外観",
        "Notifications": "通知",
        "Language": "言語",
        "Share": "共有",
        "Support": "サポート",
        "Contact": "お問い合わせ",
        "Copyright Info": "著作権情報",
        "Log Out": "ログアウト",
        "Light": "ライト",
        "Dark": "ダーク",
        "System": "システム",
        "Done": "完了",
        "Email": "メール",
        "Password": "パスワード",
        "Log In": "ログイン",
        "Forgot Password?": "パスワードを忘れた？",
        "Forgot Password": "パスワードを忘れた",
        "or": "または",
        "Continue with Google": "Googleでログイン",
        "Don't have an account?": "アカウントをお持ちでない？",
        "Sign Up": "新規登録",
        "Skip Login (Beta)": "ログインをスキップ (Beta)",
        "Email and password are required": "メールとパスワードを入力してください",
        "Authentication failed.": "認証に失敗しました",
        "Send Reset Link": "リセットリンクを送信",
        "Reset link sent!": "リセットリンクを送信しました！",
        "Please enter your email": "メールアドレスを入力してください",
    ],
    "한국어": [
        "My Holdings": "내 보유 종목",
        "News": "뉴스",
        "Gurus": "구루",
        "Guru Portfolios": "유명 투자자 포트폴리오",
        "Filing Date": "제출일",
        "Total Value": "총 가치",
        "Top Holdings": "주요 보유",
        "All Holdings": "전체 보유",
        "Company": "기업",
        "Value": "가치",
        "Shares": "주식 수",
        "Other": "기타",
        "Open": "거래 중",
        "Pre-Market": "프리마켓",
        "After-Hours": "애프터아워",
        "Closed": "휴장",
        "More": "더보기",
        "No stocks in watchlist": "관심 종목이 없습니다",
        "Enter Stock Symbol": "종목 코드 입력",
        "e.g. AAPL, MSFT": "예: AAPL, MSFT",
        "Add": "추가",
        "Cancel": "취소",
        "Orion AI": "Orion AI",
        "No conversations yet": "대화 기록이 없습니다",
        "Start a new chat": "새 대화 시작",
        "Temporary Chat": "임시 대화",
        "Thinking...": "생각 중...",
        "Ask Orion...": "Orion에게 물어보기...",
        "Photo attached": "사진 첨부됨",
        "Empty chat": "빈 대화",
        "messages": "개의 메시지",
        "Loading...": "로딩 중...",
        "AI Analysis & Trading Suggestions": "AI 분석 및 거래 제안",
        "Get AI-powered analysis and trading advice": "AI 기반 분석 및 거래 조언 받기",
        "AI Analysis": "AI 분석",
        "Ask about": "에 대해 질문",
        "Conversation": "대화",
        "Conservative": "보수적",
        "Moderate": "중립",
        "Aggressive": "공격적",
        "Generating...": "생성 중...",
        "Chart load failed": "차트 로드 실패",
        "Failed to load": "로드 실패",
        "Settings": "설정",
        "Appearance": "화면 모드",
        "Notifications": "알림",
        "Language": "언어",
        "Share": "공유",
        "Support": "지원",
        "Contact": "문의",
        "Copyright Info": "저작권 정보",
        "Log Out": "로그아웃",
        "Light": "라이트",
        "Dark": "다크",
        "System": "시스템",
        "Done": "완료",
        "Email": "이메일",
        "Password": "비밀번호",
        "Log In": "로그인",
        "Forgot Password?": "비밀번호를 잊으셨나요?",
        "Forgot Password": "비밀번호 찾기",
        "or": "또는",
        "Continue with Google": "Google로 로그인",
        "Don't have an account?": "계정이 없으신가요?",
        "Sign Up": "회원가입",
        "Skip Login (Beta)": "로그인 건너뛰기 (Beta)",
        "Email and password are required": "이메일과 비밀번호를 입력하세요",
        "Authentication failed.": "인증 실패",
        "Send Reset Link": "재설정 링크 보내기",
        "Reset link sent!": "재설정 링크를 보냈습니다!",
        "Please enter your email": "이메일을 입력하세요",
    ],
    "Español": [
        "My Holdings": "Mis Posiciones",
        "News": "Noticias",
        "Gurus": "Gurús",
        "Guru Portfolios": "Carteras de Gurús",
        "Filing Date": "Fecha",
        "Total Value": "Valor total",
        "Top Holdings": "Principales posiciones",
        "All Holdings": "Todas las posiciones",
        "Company": "Empresa",
        "Value": "Valor",
        "Shares": "Acciones",
        "Other": "Otros",
        "Open": "Abierto",
        "Pre-Market": "Pre-apertura",
        "After-Hours": "Post-cierre",
        "Closed": "Cerrado",
        "More": "Más",
        "No stocks in watchlist": "No hay acciones en la lista",
        "Enter Stock Symbol": "Ingrese símbolo",
        "e.g. AAPL, MSFT": "ej. AAPL, MSFT",
        "Add": "Agregar",
        "Cancel": "Cancelar",
        "Orion AI": "Orion AI",
        "No conversations yet": "Sin conversaciones",
        "Start a new chat": "Iniciar nuevo chat",
        "Temporary Chat": "Chat temporal",
        "Thinking...": "Pensando...",
        "Ask Orion...": "Pregunta a Orion...",
        "Photo attached": "Foto adjunta",
        "Empty chat": "Chat vacío",
        "messages": "mensajes",
        "Loading...": "Cargando...",
        "AI Analysis & Trading Suggestions": "Análisis IA y sugerencias",
        "Get AI-powered analysis and trading advice": "Obtén análisis y consejos de trading con IA",
        "AI Analysis": "Análisis IA",
        "Ask about": "Preguntar sobre",
        "Conversation": "Conversación",
        "Conservative": "Conservador",
        "Moderate": "Moderado",
        "Aggressive": "Agresivo",
        "Generating...": "Generando...",
        "Chart load failed": "Error al cargar gráfico",
        "Failed to load": "Error al cargar",
        "Settings": "Ajustes",
        "Appearance": "Apariencia",
        "Notifications": "Notificaciones",
        "Language": "Idioma",
        "Share": "Compartir",
        "Support": "Soporte",
        "Contact": "Contacto",
        "Copyright Info": "Derechos de autor",
        "Log Out": "Cerrar sesión",
        "Light": "Claro",
        "Dark": "Oscuro",
        "System": "Sistema",
        "Done": "Listo",
        "Email": "Correo",
        "Password": "Contraseña",
        "Log In": "Iniciar sesión",
        "Forgot Password?": "¿Olvidaste tu contraseña?",
        "Forgot Password": "Olvidé mi contraseña",
        "or": "o",
        "Continue with Google": "Continuar con Google",
        "Don't have an account?": "¿No tienes cuenta?",
        "Sign Up": "Registrarse",
        "Skip Login (Beta)": "Omitir inicio (Beta)",
        "Email and password are required": "Correo y contraseña requeridos",
        "Authentication failed.": "Autenticación fallida",
        "Send Reset Link": "Enviar enlace",
        "Reset link sent!": "¡Enlace enviado!",
        "Please enter your email": "Ingrese su correo",
    ],
    "Français": [
        "My Holdings": "Mes Positions",
        "Gurus": "Gourous",
        "Guru Portfolios": "Portefeuilles des Gourous",
        "Filing Date": "Date",
        "Total Value": "Valeur totale",
        "Top Holdings": "Principales positions",
        "All Holdings": "Toutes les positions",
        "Company": "Entreprise",
        "Value": "Valeur",
        "Shares": "Actions",
        "Other": "Autres",
        "Open": "Ouvert",
        "Pre-Market": "Pré-ouverture",
        "After-Hours": "Après-clôture",
        "Closed": "Fermé",
        "News": "Actualités",
        "More": "Plus",
        "No stocks in watchlist": "Aucune action dans la liste",
        "Enter Stock Symbol": "Entrez le symbole",
        "e.g. AAPL, MSFT": "ex. AAPL, MSFT",
        "Add": "Ajouter",
        "Cancel": "Annuler",
        "Orion AI": "Orion AI",
        "No conversations yet": "Aucune conversation",
        "Start a new chat": "Nouveau chat",
        "Temporary Chat": "Chat temporaire",
        "Thinking...": "Réflexion...",
        "Ask Orion...": "Demandez à Orion...",
        "Photo attached": "Photo jointe",
        "Empty chat": "Chat vide",
        "messages": "messages",
        "Loading...": "Chargement...",
        "AI Analysis & Trading Suggestions": "Analyse IA et suggestions",
        "Get AI-powered analysis and trading advice": "Obtenez une analyse et des conseils IA",
        "AI Analysis": "Analyse IA",
        "Ask about": "Demander sur",
        "Conversation": "Conversation",
        "Conservative": "Conservateur",
        "Moderate": "Modéré",
        "Aggressive": "Agressif",
        "Generating...": "Génération...",
        "Chart load failed": "Échec du chargement",
        "Failed to load": "Échec du chargement",
        "Settings": "Paramètres",
        "Appearance": "Apparence",
        "Notifications": "Notifications",
        "Language": "Langue",
        "Share": "Partager",
        "Support": "Support",
        "Contact": "Contact",
        "Copyright Info": "Droits d'auteur",
        "Log Out": "Déconnexion",
        "Light": "Clair",
        "Dark": "Sombre",
        "System": "Système",
        "Done": "Terminé",
        "Email": "E-mail",
        "Password": "Mot de passe",
        "Log In": "Se connecter",
        "Forgot Password?": "Mot de passe oublié ?",
        "Forgot Password": "Mot de passe oublié",
        "or": "ou",
        "Continue with Google": "Continuer avec Google",
        "Don't have an account?": "Pas de compte ?",
        "Sign Up": "S'inscrire",
        "Skip Login (Beta)": "Passer (Beta)",
        "Email and password are required": "E-mail et mot de passe requis",
        "Authentication failed.": "Échec de l'authentification",
        "Send Reset Link": "Envoyer le lien",
        "Reset link sent!": "Lien envoyé !",
        "Please enter your email": "Entrez votre e-mail",
    ],
    "Deutsch": [
        "My Holdings": "Meine Positionen",
        "News": "Nachrichten",
        "Gurus": "Gurus",
        "Guru Portfolios": "Guru-Portfolios",
        "Filing Date": "Datum",
        "Total Value": "Gesamtwert",
        "Top Holdings": "Top-Positionen",
        "All Holdings": "Alle Positionen",
        "Company": "Unternehmen",
        "Value": "Wert",
        "Shares": "Aktien",
        "Other": "Sonstige",
        "Open": "Geöffnet",
        "Pre-Market": "Vorbörslich",
        "After-Hours": "Nachbörslich",
        "Closed": "Geschlossen",
        "More": "Mehr",
        "No stocks in watchlist": "Keine Aktien in der Watchlist",
        "Enter Stock Symbol": "Aktiensymbol eingeben",
        "e.g. AAPL, MSFT": "z.B. AAPL, MSFT",
        "Add": "Hinzufügen",
        "Cancel": "Abbrechen",
        "Orion AI": "Orion AI",
        "No conversations yet": "Keine Gespräche",
        "Start a new chat": "Neuen Chat starten",
        "Temporary Chat": "Temporärer Chat",
        "Thinking...": "Denke nach...",
        "Ask Orion...": "Frage Orion...",
        "Photo attached": "Foto angehängt",
        "Empty chat": "Leerer Chat",
        "messages": "Nachrichten",
        "Loading...": "Laden...",
        "AI Analysis & Trading Suggestions": "KI-Analyse & Handelsvorschläge",
        "Get AI-powered analysis and trading advice": "KI-gestützte Analyse und Handelsberatung",
        "AI Analysis": "KI-Analyse",
        "Ask about": "Fragen zu",
        "Conversation": "Gespräch",
        "Conservative": "Konservativ",
        "Moderate": "Moderat",
        "Aggressive": "Aggressiv",
        "Generating...": "Generierung...",
        "Chart load failed": "Diagramm fehlgeschlagen",
        "Failed to load": "Laden fehlgeschlagen",
        "Settings": "Einstellungen",
        "Appearance": "Erscheinungsbild",
        "Notifications": "Benachrichtigungen",
        "Language": "Sprache",
        "Share": "Teilen",
        "Support": "Hilfe",
        "Contact": "Kontakt",
        "Copyright Info": "Urheberrecht",
        "Log Out": "Abmelden",
        "Light": "Hell",
        "Dark": "Dunkel",
        "System": "System",
        "Done": "Fertig",
        "Email": "E-Mail",
        "Password": "Passwort",
        "Log In": "Anmelden",
        "Forgot Password?": "Passwort vergessen?",
        "Forgot Password": "Passwort vergessen",
        "or": "oder",
        "Continue with Google": "Weiter mit Google",
        "Don't have an account?": "Kein Konto?",
        "Sign Up": "Registrieren",
        "Skip Login (Beta)": "Login überspringen (Beta)",
        "Email and password are required": "E-Mail und Passwort erforderlich",
        "Authentication failed.": "Authentifizierung fehlgeschlagen",
        "Send Reset Link": "Link senden",
        "Reset link sent!": "Link gesendet!",
        "Please enter your email": "Bitte E-Mail eingeben",
    ],
    "Português": [
        "My Holdings": "Minhas Posições",
        "News": "Notícias",
        "Gurus": "Gurus",
        "Guru Portfolios": "Portfólios dos Gurus",
        "Filing Date": "Data",
        "Total Value": "Valor total",
        "Top Holdings": "Principais posições",
        "All Holdings": "Todas as posições",
        "Company": "Empresa",
        "Value": "Valor",
        "Shares": "Ações",
        "Other": "Outros",
        "Open": "Aberto",
        "Pre-Market": "Pré-mercado",
        "After-Hours": "Pós-mercado",
        "Closed": "Fechado",
        "More": "Mais",
        "No stocks in watchlist": "Nenhuma ação na lista",
        "Enter Stock Symbol": "Digite o símbolo",
        "Add": "Adicionar",
        "Cancel": "Cancelar",
        "No conversations yet": "Sem conversas",
        "Start a new chat": "Novo chat",
        "Temporary Chat": "Chat temporário",
        "Thinking...": "Pensando...",
        "Ask Orion...": "Pergunte ao Orion...",
        "Photo attached": "Foto anexada",
        "messages": "mensagens",
        "Loading...": "Carregando...",
        "AI Analysis & Trading Suggestions": "Análise IA e sugestões",
        "Get AI-powered analysis and trading advice": "Obtenha análise e conselhos com IA",
        "AI Analysis": "Análise IA",
        "Ask about": "Perguntar sobre",
        "Conversation": "Conversa",
        "Conservative": "Conservador",
        "Moderate": "Moderado",
        "Aggressive": "Agressivo",
        "Generating...": "Gerando...",
        "Settings": "Configurações",
        "Appearance": "Aparência",
        "Notifications": "Notificações",
        "Language": "Idioma",
        "Share": "Compartilhar",
        "Support": "Suporte",
        "Contact": "Contato",
        "Copyright Info": "Direitos autorais",
        "Log Out": "Sair",
        "Light": "Claro",
        "Dark": "Escuro",
        "System": "Sistema",
        "Done": "Concluído",
        "Log In": "Entrar",
        "Forgot Password?": "Esqueceu a senha?",
        "or": "ou",
        "Continue with Google": "Continuar com Google",
        "Don't have an account?": "Não tem conta?",
        "Sign Up": "Cadastrar",
    ],
    "Italiano": [
        "My Holdings": "Le Mie Posizioni",
        "News": "Notizie",
        "Gurus": "Guru",
        "Guru Portfolios": "Portafogli dei Guru",
        "Filing Date": "Data",
        "Total Value": "Valore totale",
        "Top Holdings": "Principali posizioni",
        "All Holdings": "Tutte le posizioni",
        "Company": "Azienda",
        "Value": "Valore",
        "Shares": "Azioni",
        "Other": "Altri",
        "Open": "Aperto",
        "Pre-Market": "Pre-apertura",
        "After-Hours": "Dopo-chiusura",
        "Closed": "Chiuso",
        "More": "Altro",
        "No stocks in watchlist": "Nessuna azione nella lista",
        "Enter Stock Symbol": "Inserisci simbolo",
        "Add": "Aggiungi",
        "Cancel": "Annulla",
        "No conversations yet": "Nessuna conversazione",
        "Start a new chat": "Nuova chat",
        "Temporary Chat": "Chat temporanea",
        "Thinking...": "Sto pensando...",
        "Ask Orion...": "Chiedi a Orion...",
        "Photo attached": "Foto allegata",
        "messages": "messaggi",
        "Loading...": "Caricamento...",
        "AI Analysis & Trading Suggestions": "Analisi IA e suggerimenti",
        "Get AI-powered analysis and trading advice": "Ottieni analisi e consigli di trading con IA",
        "AI Analysis": "Analisi IA",
        "Ask about": "Chiedi su",
        "Conversation": "Conversazione",
        "Conservative": "Conservativo",
        "Moderate": "Moderato",
        "Aggressive": "Aggressivo",
        "Generating...": "Generazione...",
        "Settings": "Impostazioni",
        "Appearance": "Aspetto",
        "Notifications": "Notifiche",
        "Language": "Lingua",
        "Share": "Condividi",
        "Support": "Supporto",
        "Contact": "Contatto",
        "Copyright Info": "Copyright",
        "Log Out": "Esci",
        "Light": "Chiaro",
        "Dark": "Scuro",
        "System": "Sistema",
        "Done": "Fatto",
        "Log In": "Accedi",
        "Forgot Password?": "Password dimenticata?",
        "or": "o",
        "Continue with Google": "Continua con Google",
        "Don't have an account?": "Non hai un account?",
        "Sign Up": "Registrati",
    ],
    "Русский": [
        "My Holdings": "Мои активы",
        "News": "Новости",
        "Gurus": "Гуру",
        "Guru Portfolios": "Портфели гуру",
        "Filing Date": "Дата",
        "Total Value": "Общая стоимость",
        "Top Holdings": "Топ позиции",
        "All Holdings": "Все позиции",
        "Company": "Компания",
        "Value": "Стоимость",
        "Shares": "Акции",
        "Other": "Прочее",
        "Open": "Открыто",
        "Pre-Market": "Премаркет",
        "After-Hours": "Постмаркет",
        "Closed": "Закрыто",
        "More": "Ещё",
        "No stocks in watchlist": "Нет акций в списке",
        "Enter Stock Symbol": "Введите тикер",
        "Add": "Добавить",
        "Cancel": "Отмена",
        "No conversations yet": "Нет бесед",
        "Start a new chat": "Новый чат",
        "Temporary Chat": "Временный чат",
        "Thinking...": "Думаю...",
        "Ask Orion...": "Спросите Orion...",
        "Photo attached": "Фото прикреплено",
        "messages": "сообщений",
        "Loading...": "Загрузка...",
        "AI Analysis & Trading Suggestions": "ИИ-анализ и рекомендации",
        "Get AI-powered analysis and trading advice": "Получите ИИ-анализ и торговые рекомендации",
        "AI Analysis": "ИИ-анализ",
        "Ask about": "Спросить о",
        "Conversation": "Диалог",
        "Conservative": "Консервативный",
        "Moderate": "Умеренный",
        "Aggressive": "Агрессивный",
        "Generating...": "Генерация...",
        "Settings": "Настройки",
        "Appearance": "Оформление",
        "Notifications": "Уведомления",
        "Language": "Язык",
        "Share": "Поделиться",
        "Support": "Поддержка",
        "Contact": "Контакты",
        "Copyright Info": "Авторские права",
        "Log Out": "Выйти",
        "Light": "Светлая",
        "Dark": "Тёмная",
        "System": "Системная",
        "Done": "Готово",
        "Log In": "Войти",
        "Forgot Password?": "Забыли пароль?",
        "or": "или",
        "Continue with Google": "Войти через Google",
        "Don't have an account?": "Нет аккаунта?",
        "Sign Up": "Регистрация",
    ],
    "العربية": [
        "My Holdings": "محفظتي",
        "News": "الأخبار",
        "Gurus": "المستثمرون",
        "Guru Portfolios": "محافظ المستثمرين",
        "Filing Date": "التاريخ",
        "Total Value": "القيمة الإجمالية",
        "Top Holdings": "أكبر الممتلكات",
        "All Holdings": "جميع الممتلكات",
        "Company": "الشركة",
        "Value": "القيمة",
        "Shares": "الأسهم",
        "Other": "أخرى",
        "Open": "مفتوح",
        "Pre-Market": "ما قبل السوق",
        "After-Hours": "ما بعد السوق",
        "Closed": "مغلق",
        "More": "المزيد",
        "No stocks in watchlist": "لا توجد أسهم في القائمة",
        "Enter Stock Symbol": "أدخل رمز السهم",
        "Add": "إضافة",
        "Cancel": "إلغاء",
        "No conversations yet": "لا توجد محادثات",
        "Start a new chat": "بدء محادثة جديدة",
        "Temporary Chat": "محادثة مؤقتة",
        "Thinking...": "جارٍ التفكير...",
        "Ask Orion...": "...اسأل Orion",
        "Photo attached": "صورة مرفقة",
        "messages": "رسائل",
        "Loading...": "جارٍ التحميل...",
        "AI Analysis & Trading Suggestions": "تحليل الذكاء الاصطناعي",
        "Get AI-powered analysis and trading advice": "احصل على تحليل ونصائح تداول بالذكاء الاصطناعي",
        "AI Analysis": "تحليل AI",
        "Ask about": "اسأل عن",
        "Conversation": "محادثة",
        "Conservative": "محافظ",
        "Moderate": "معتدل",
        "Aggressive": "عدواني",
        "Generating...": "جارٍ الإنشاء...",
        "Settings": "الإعدادات",
        "Appearance": "المظهر",
        "Notifications": "الإشعارات",
        "Language": "اللغة",
        "Share": "مشاركة",
        "Support": "الدعم",
        "Contact": "اتصل بنا",
        "Copyright Info": "حقوق النشر",
        "Log Out": "تسجيل الخروج",
        "Light": "فاتح",
        "Dark": "داكن",
        "System": "النظام",
        "Done": "تم",
        "Log In": "تسجيل الدخول",
        "Forgot Password?": "نسيت كلمة المرور؟",
        "or": "أو",
        "Continue with Google": "المتابعة مع Google",
        "Don't have an account?": "ليس لديك حساب؟",
        "Sign Up": "إنشاء حساب",
    ],
    "हिन्दी": [
        "My Holdings": "मेरी होल्डिंग्स",
        "News": "समाचार",
        "Gurus": "गुरु",
        "Guru Portfolios": "गुरु पोर्टफोलियो",
        "Filing Date": "तारीख",
        "Total Value": "कुल मूल्य",
        "Top Holdings": "शीर्ष होल्डिंग्स",
        "All Holdings": "सभी होल्डिंग्स",
        "Company": "कंपनी",
        "Value": "मूल्य",
        "Shares": "शेयर",
        "Other": "अन्य",
        "Open": "खुला",
        "Pre-Market": "प्री-मार्केट",
        "After-Hours": "आफ्टर-आवर्स",
        "Closed": "बंद",
        "More": "अधिक",
        "No stocks in watchlist": "वॉचलिस्ट में कोई स्टॉक नहीं",
        "Enter Stock Symbol": "स्टॉक सिंबल दर्ज करें",
        "Add": "जोड़ें",
        "Cancel": "रद्द करें",
        "No conversations yet": "कोई बातचीत नहीं",
        "Start a new chat": "नई चैट शुरू करें",
        "Temporary Chat": "अस्थायी चैट",
        "Thinking...": "सोच रहा हूँ...",
        "Ask Orion...": "Orion से पूछें...",
        "Photo attached": "फ़ोटो संलग्न",
        "messages": "संदेश",
        "Loading...": "लोड हो रहा है...",
        "AI Analysis & Trading Suggestions": "AI विश्लेषण और सुझाव",
        "Get AI-powered analysis and trading advice": "AI विश्लेषण और ट्रेडिंग सलाह प्राप्त करें",
        "AI Analysis": "AI विश्लेषण",
        "Ask about": "के बारे में पूछें",
        "Conversation": "बातचीत",
        "Conservative": "रूढ़िवादी",
        "Moderate": "मध्यम",
        "Aggressive": "आक्रामक",
        "Generating...": "जनरेट हो रहा है...",
        "Settings": "सेटिंग्स",
        "Appearance": "थीम",
        "Notifications": "सूचनाएँ",
        "Language": "भाषा",
        "Share": "शेयर करें",
        "Support": "सहायता",
        "Contact": "संपर्क",
        "Copyright Info": "कॉपीराइट",
        "Log Out": "लॉग आउट",
        "Light": "लाइट",
        "Dark": "डार्क",
        "System": "सिस्टम",
        "Done": "हो गया",
        "Log In": "लॉग इन",
        "Forgot Password?": "पासवर्ड भूल गए?",
        "or": "या",
        "Continue with Google": "Google से जारी रखें",
        "Don't have an account?": "खाता नहीं है?",
        "Sign Up": "साइन अप",
    ],
]
